apiVersion: v1
kind: Service
metadata:
  name: backend-v2
  namespace: facedetect
  labels:
    app: backend-v2
    service: backend-v2
spec:
  ports:
  - name: http
    port: 5001
    targetPort: http
  selector:
    app: backend-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  namespace: facedetect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-v2
  template:
    metadata:
      labels:
        app: backend-v2
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name:  backend-v2
          image: docker.io/bistrulli/backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5001
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-v2-dstrule
  namespace: facedetect
spec:
  host: backend-v2.facedetect.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: RANDOM
    outlierDetection:
      consecutiveGatewayErrors: 5
      interval: 10s
      baseEjectionTime: 6m
---