apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: facedetect
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 31111
    targetPort: http
    name: http
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: facedetect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      #imagePullSecrets:
      #  - name: gitlab-auth
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #    - labelSelector:
      #        matchExpressions:
      #        - key: app
      #          operator: In
      #          values:
      #          - backend-v1
      #          - backend-v2
      #          - storage
      #      topologyKey: "kubernetes.io/hostname"
      #      namespaces:
      #        - facedetect
      containers:
      - name:  frontend
        image: bistrulli/frontend:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
