apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: facedetect
  labels:
    app: storage
    service: storage
spec:
  ports:
  - name: http
    port: 5002
    targetPort: http
  selector:
    app: storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  namespace: facedetect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      #imagePullSecrets:
      #  - name: gitlab-auth
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - backend-v1
                - backend-v2
                - frontend
            topologyKey: "kubernetes.io/hostname"
            namespaces:
              - facedetect
      containers:
      - name:  storage
        image: registry.gitlab.com/PATH_TO_REGISTRY/storage:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 5002
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      - name: redis
        image: redis:6.2.6
        ports:
          - name: http
            containerPort: 6379
      
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: storage-dstrule
  namespace: facedetect
spec:
  host: storage.facedetect.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: RANDOM
    outlierDetection:
      consecutiveGatewayErrors: 5
      interval: 10s
      baseEjectionTime: 6m
